name: lintNtest

on:
  pull_request:
    branches: [ "main", "dev" ]
jobs:
  run-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Installing Dependencies
        run: npm install
    
      - name: Running Eslint
        run: npm run lint
      
      - name: Running tests
        run: npm run tests

