name: lintNtest

on:
  pull_request:
    branches: [ "main", "dev" ]
jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Installing Dependencies
        run: npm install
  
  run-linter:
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - name: Running Eslint
        run: npm run lint
  
  run-tests:
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - name: Running tests
        run: npm run tests

